apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: compute-plans
  namespace: ovh-pricelist
spec:
  schedule: 0 1 * * 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: compute-plans
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            lifecycle:
              postStart:
                command:
                - /bin/bash
                - -c
                - |
                for file in all privatecloud publiccloud utils baremetal; do 
                  wget "https://share.s3.gra.io.cloud.ovh.net/jobs/${file}.py"
                done
          - command:
            - python3
            - all.py
            image: tdr2d/ovh_pricelist:2.4.0-job
            name: compute-plans
            envFrom:
            - secretRef:
                name: s3-share-secrets
          restartPolicy: Never
